### ISSUE TITLE
panic occurs if git(1) is not installed

### ISSUE THREAD

**Issue by gfx** [x-motemen/ghq#277]
Some distributions, e.g. Ubuntu 16.04 server, have no `git` installed by default.  This issue occurs in such a situation and `panic` is really confusing, so it would be great if more readable messages were shown.

```
$ ghq list
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.urlMatchLocalRepositoryRoots(0xc0000f9760, 0x2, 0x2, 0xc0000a6900, 0x13)
	/home/runner/work/ghq/ghq/local_repository.go:417 +0x31f
main.localRepositoryRoots.func1()
	/home/runner/work/ghq/ghq/local_repository.go:371 +0x494
sync.(*Once).doSlow(0xc127b8, 0xc0000f98b8)
	/opt/hostedtoolcache/go/1.14.0-beta1/x64/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.14.0-beta1/x64/src/sync/once.go:57
main.localRepositoryRoots(0x1, 0x20, 0x8394c0, 0x4, 0x5, 0x20)
	/home/runner/work/ghq/ghq/local_repository.go:341 +0xaa
main.walkLocalRepositories(0x0, 0x0, 0xc00009b200, 0x0, 0x0)
	/home/runner/work/ghq/ghq/local_repository.go:249 +0x38
main.doList(0xc0000acd00, 0x5, 0x8)
	/home/runner/work/ghq/ghq/cmd_list.go:56 +0x2a7
github.com/urfave/cli/v2.(*Command).Run(0xbdfea0, 0xc0000acac0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/command.go:161 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc00009e300, 0x9142e0, 0xc0000a4010, 0xc00009a020, 0x2, 0x2, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:302 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
	/home/runner/work/ghq/ghq/main.go:16 +0x67
```

**Comment by Songmu** [comment]
Thanks for the report. Sorry for the slow response.

I updated Songmu/gitconfig in #295 and this issue should be resolved along with it. Please check.

**Comment by gfx** [comment]
Thanks! 👏
